### ISSUE TITLE
A Bug in the MappetExtra Mod Version 1.4.3 make the GUI of Oxygen Daily Rewards Broken

### ISSUE THREAD

**Issue by Titoo8899** [TorayLife/MappetExtras#49]
Hi,
I love your mod and the many thinks what you have added to the Mod. But I have a Big Problem in your mod found. Then I play with the MappetExtra Mod and the Oxygen Daily Reward Mod the GUI of the Oxygen Daily Reward Broke. Then I have your mod not install the GUI is normal of the Oxygen Daily Reward Mod. I hope you can this mod in the next version fix. I have 2 Pictures make. One with your mod in the Mods folder the other not with your mod. I hope you find the Problem in your mod and can fix it.

Mods:
- mclib-2.4.2-1.12.2
- mappet-0.9-1.12.2
- mappetExtras-1.4.3-1.12.2
- blockbuster-2.6.1-1.12.2
- metamorph-1.3.1-1.12.2
- oxygen-core-1.12.2-0.11.4 - Link: https://www.curseforge.com/minecraft/mc-mods/oxygen-core
- oxygen-daily-rewards-1.12.2-0.11.2 - Link: https://www.curseforge.com/minecraft/mc-mods/oxygen-daily-rewards

Picture 1 show the GUI of the Oxygen Daily Reward alone (MappetExtra Mod not installed!!!) + the Required Mods
![2024-04-05_18 29 09](https://github.com/TorayLife/MappetExtras/assets/42325138/26a34b1c-ab63-40e2-83f0-48947ee7e447)

Picture 2 show the GUI with the Oxygen Daily Reward and the MappedExtra Mod then this 2 was installed + the Required Mods
![2024-04-05_18 41 24](https://github.com/TorayLife/MappetExtras/assets/42325138/833d2035-fedb-408c-8c3c-57694200a831)

**Comment by Erfram** [comment]
Hi! You can build the mod from Github and everything will be fixed. But keep in mind that the API for the camera, hands and minecraft hoods will disappear. All the goodies with rendering have been transferred to another mod

**Comment by Titoo8899** [comment]
Okay and how can I this make I have from github and her function not the knowledge

**Comment by Erfram** [comment]
I can send you the mod itself on discord

**Comment by Titoo8899** [comment]
yes send me the mod on Discord. My name on Discord is Titoo8899

**Comment by Titoo8899** [comment]
I will see then you have send me the mod of her function and then all thinks was good then I can close this her. And thanks for your help I hope the mod help.

**Comment by Titoo8899** [comment]
Sorry the first t was not the Big T

**Comment by Titoo8899** [comment]
But one little question have I how long must you work to create so a mod what can fix the mod?
