### ISSUE TITLE
Mod needs MixinBooter, i've downloaded it but MappetExtras still doesnt work and shows me that i neen MixinBooter.

### ISSUE THREAD

**Issue by AlexHysel** [TorayLife/MappetExtras#50]

**Comment by MRkto** [comment]
did you download mixin booter from this site? https://www.curseforge.com/minecraft/mc-mods/mixin-booter

**Comment by AlexHysel** [comment]
> did you download mixin booter from this site? https://www.curseforge.com/minecraft/mc-mods/mixin-booter

I downloaded it from CurseForge app

**Comment by MRkto** [comment]
I haven't used CurseForge app can you send a list of mods

**Comment by MRkto** [comment]
It might be worth trying version 8.8

**Comment by AlexHysel** [comment]
> I haven't used CurseForge app can you send a list of mods
![explorer_11GMQXu0AT](https://github.com/TorayLife/MappetExtras/assets/174929690/9c56aa17-cc30-4f89-b930-994292a72b3a)

**Comment by MRkto** [comment]
I apologize for forgetting to answer, I can not answer exactly why this happens I can only advise to remove everything that does not apply to mappet and check it like this

**Comment by AlexHysel** [comment]
> I apologize for forgetting to answer, I can not answer exactly why this happens I can only advise to remove everything that does not apply to mappet and check it like this

Thanks, no it works. I deleted "Phosphor (forge)" and replaced "LittleTiles" with "Chisels & Bits".

**Comment by AlexHysel** [comment]
I deleted "Phosphor (forge)" and replaced "LittleTiles" with "Chisels & Bits" and now it works.
